services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.samuelsjoen_no.loadbalancer.server.port=80"
      - "traefik.http.routers.samuelsjoen_no.rule=Host(`samuelsjoen.no`, `www.samuelsjoen.no`)"
      - "traefik.http.routers.samuelsjoen_no.tls.certresolver=letsencrypt"
    volumes:
      - ./static/images:/usr/share/nginx/html/images
    networks:
      - web
      - default

  backend:
    build:
      context: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: production
    networks:
      - web
      - default
    volumes:
      - ./static:/app/src/main/resources/static
      - ./backend/samuelsjoen.db:/app/samuelsjoen.db

networks:
  web:
    external: true
